compatibility_date = "2025-06-07"
main = "build/worker/shim.mjs"
name = "cf-workers-api"

[build]
command = """
  cargo install -q worker-build && worker-build --release --package cf-workers-api
  """
