[package]
name = "learning-axum"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.88"
axum = "0.8.3"
const-str = "0.6.2"
s3s = "0.11.0"
serde_json = "1.0.140"
tower = "0.5.2"
tracing = "0.1.41"
